apiVersion: v1
kind: Service
metadata:
  name: portal-in
  labels:
    run: portal-in
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: fjord
  